### ISSUE TITLE
Poster-Größe

### ISSUE THREAD

**Issue by MaximilianFeldmann** [fberghahn/EPWS2122Feldmann-Berghahn#2]
Hi,
die DIN A1 Größe im Styleguide (Figma, 1683 x 2383 Pixel) entspricht nicht dem Standart Format von 7016 x 9933 Pixel. Wodurch entsteht dieser Unterschied? Hat das mit dpi und ppi zu tun? Welche Pixelmaße sind die Gewünschten für das Bearbeiten in Photoshop?

MfG
Maximilian & Florian

**Comment by slschulte** [comment]
Hi,
ich kann mir das auch nur über die dpi erklären. bei 72dpi würde die Größe ja ziemlich genau passen.
Bezüglich der Bearbeitung in Photoshop haben wir keine Vorgaben an euch. Hauptsache es kommt hinterher ein lesbares Poster in A1 Größe dabei heraus.
Beste Grüße,
Simon
