### ISSUE TITLE
Tipp für Audit4

### ISSUE THREAD

**Issue by umuesse** [fberghahn/EPWS2122Feldmann-Berghahn#3]
Hi ihr beiden, 

ich wollte euch auch eben noch den Tipp mit an die Hand geben, dass es sinnvoll sein kann, ein Screenvideo von eurem UseCase zu machen. Wir haben es schon einige Male mitbekommen, dass genau im Audit der Prototyp nicht funktioniert und das wäre sauärgerlich. Es ist keine Pflicht, dient lediglich eurer Sicherheit.

VG
Uwe

**Comment by fberghahn** [comment]
Danke für den Tipp ist aufgenommen.  
Beste Grüße
